version: "3.9"

services:
  ssh-db:
    container_name: ssh_db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5434'
    volumes:
      - ssh-db:/var/lib/postgresql/data
    networks:
      - ssh
    command:
      - -p 5434

  ssh-liquid:
    container_name: ssh_liquid
    image: liquibase/liquibase
    command: --changeLogFile=/change-log.xml update --url=jdbc:postgresql://ssh-db:5434/postgres --username=postgres --password=postgres
    volumes:
      - ./src/main/resources/db/change-log.xml:/liquibase/change-log.xml
      - ./src/main/resources/db/entities/:/liquibase/entities/
    networks:
      - ssh
networks:
  ssh:
volumes:
  ssh-db:
